# Evaluation 1

This evaluation is based on python object oriented programming and python datascience libraries.

In the code block below, pandas library is used for reading a csv file. This file contains data for sepal and petal dimensions for different species for the iris flower. read_csv functions loads the csv file into a DataFrame object. DataFrame objects have their own set of fucntions for manupilation and processing data. For the purpose of this evaluation the numerical data from the dataset is converted into a numpy array (using .values method). based on this numpy array answer the below questions

In [3]:
import numpy as np
import pandas as pd


data = pd.read_csv("Iris.csv")

data_array = data[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']].values
#data_array

##### Q1.a What is the shape of data_array? Find the mean for all columns. **Do not use for loops**

In [4]:
##save result in a new variable
shape = data_array.shape
print(shape)
means = data_array.sum(axis=0)/shape[0]
print(means)

(150, 4)
[5.84333333 3.054      3.75866667 1.19866667]


##### Q1.b substract the columns means from their respective columns such that the new column means are zero. **Do not use for loops**

In [5]:
new_data = data_array - means
new_means = new_data.sum(axis=0)/shape[0]
new_means.round(2)

array([-0., -0.,  0., -0.])

##### Q1.c Find the distance of all data samples from the mean. **Do not use for loops** Hint uses vectorization. 
dsitance between two vectors is given by: 
$d(x1,x2) = \sqrt{\sum{_{p}(x1_p -x2_p)^2}}$ 

Where p is the number of elements (dimension) of the vectors

In [6]:
diff_squared = (data_array - means)**2
sum_dist = diff_squared.sum(axis=1)

In the code block bellow Pillow library is used to read image. The image is loaded as Pillow Image object. To use numpy operations on this object it is converted into a numpy array.

The resulting numpy array will have the shape (H,W,C) where H is the height W is the width and C is the number of channels. Channel format RGB (Red Green and Blue) is most common. Pil reads jpeg image in RGB fromat. Some other formats are single channel (grayscale image) or RGBA (read green blue alpha) where A is the alpha channel used for transperency values. 

In [25]:
from PIL import Image

img = np.array(Image.open("lenna.jpg"))

##### Q2.a Find the channel wise mean and standard deviation (std). **Do not use for loops**

In [23]:
channel_wise_mean = np.mean(img, axis=(0,1))
channel_wise_std = np.std(img, axis=(0,1))
channel_wise_mean

array([177.18261728,  95.38548148, 101.22575802])

##### Q2.b Standardize the image i.e substract the per channel mean and divide by per channel std. **Do not use for loops**

In [26]:
img_normal = (img - channel_wise_mean)/channel_wise_std

##### Q2.c Use OpenCV to read the same image and find channel wise mean and std. Is there a differnece ?

In [28]:
import cv2
img_ = cv2.imread("lenna.jpg", cv2.IMREAD_COLOR)
norm_image = cv2.normalize(img_, None, alpha=0, beta=1, norm_type=cv2.NORM_MINMAX, dtype=cv2.CV_32F)


ModuleNotFoundError: No module named 'cv2'

In machine learning comparing differrent models requires to have a evaluations metric on some test or valiation data. This data is split from the original data before the models are trained on it to evaluate the genrelization ability. Usually 10 to 20 percent data is reserved for validation/testing. Scikit learn provides fucntion for this purpose. 

In [64]:
X_data = data[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']].values #features used for prediction (independent variable)
label  = data[['Species']] #label or target which will be predicted (dependent variable)
label

Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 1 columns]

##### Q3 Split the X_data and label into train and validation sets with 20 percent data in validation set. Make sure that the split is random. However the same random split should be reproducible every run. Use scikit learn to split

In [68]:
from sklearn.model_selection import train_test_split
labels = np.array(label)
#print(labels)
x_train, x_val, label_train, label_val = train_test_split(X_data, labels, train_size=0.2, random_state=1)
x_train, x_val, label_train, label_val

(array([[4.6, 3.2, 1.4, 0.2],
        [6.4, 3.2, 5.3, 2.3],
        [4.3, 3. , 1.1, 0.1],
        [5.6, 3. , 4.1, 1.3],
        [4.4, 2.9, 1.4, 0.2],
        [5.5, 2.4, 3.7, 1. ],
        [5. , 2. , 3.5, 1. ],
        [5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.9, 2.4, 3.3, 1. ],
        [4.6, 3.6, 1. , 0.2],
        [5.9, 3. , 4.2, 1.5],
        [6.1, 2.9, 4.7, 1.4],
        [5. , 3.4, 1.5, 0.2],
        [6.7, 3.1, 4.7, 1.5],
        [5.7, 2.9, 4.2, 1.3],
        [6.2, 2.2, 4.5, 1.5],
        [7. , 3.2, 4.7, 1.4],
        [5.8, 2.7, 5.1, 1.9],
        [5.4, 3.4, 1.7, 0.2],
        [5. , 3. , 1.6, 0.2],
        [6.1, 2.6, 5.6, 1.4],
        [6.1, 2.8, 4. , 1.3],
        [7.2, 3. , 5.8, 1.6],
        [5.7, 2.6, 3.5, 1. ],
        [6.3, 2.8, 5.1, 1.5],
        [6.4, 3.1, 5.5, 1.8],
        [6.3, 2.5, 4.9, 1.5],
        [6.7, 3.1, 5.6, 2.4],
        [4.9, 3.1, 1.5, 0.1]]), array([[5.8, 4. , 1.2, 0.2],
        [5.1, 2.5, 3. , 1.1],
        [6.6, 3. , 4.4, 1.4],
        [

##### Q4 Object oriented programming in python

##### Q4.a
In object detection the ouput of the algorithm is a bounding box around the objects that are detected as shown below.

![](sample.jpg "Sample detections from an object detector")

There are multiple formats for bounding boxes. Two of the common ones are xywh (x y of top left point of the box and width and height) and xyxy (top left and bottom right x and y coordinates). 

Create an object called bbox that takes in a list of length 4 as inputs. these are are four points of the box. It should also take in input a string called mode which can be either "xywh" or "xyxy" depending on the format. This objects should have the following methods 1. xyxy_to_xywh that converts from xyxy format to xywh 2. xywh_to_xyxy 3. area that finds area of bbox 4. is_in that takes input another bbox object and returns true if the current bbox is inside the input bbox.

further if print is used on the object it should print the xyxy coordinates  and area. "+" operator should add areas of two bounding boxes. square brackets "[]" should index accordingly. For eg bbox[0] should return x1 (top left x co-ordinate)  and bbox[2] should return w if mode is xywh else return x2 (bottom right x co-ordinate).    


In [30]:
class bbox():
    def __init__(self, lst, mode):
        self.mode = mode
        self.top_left = [lst[0], lst[1]]
        self.lst = lst
        if mode=="xywh":
            self.w = lst[2]
            self.h = lst[3]
            self.bottom_right = [self.top_left[0] + self.w, self.top_left[1] + self.h]
        else:
            self.bottom_right = [lst[2], lst[3]]
            self.w = self.bottom_right[0] - self.top_left[0]
            self.h = self.bottom_right[1] - self.top_left[1]
            
    def __str__(self):
        coords = self.top_left + self.bottom_right
        area = self.area()
        return "{}, {}".format(coords, area)
    
    def __add__(self, other):
        return self.area() + other.area()
    
    def __getitem__(self, index):
        return self.lst[index]
        
            
    def xyxy_to_xywh(self):
        self.mode = "xywh"
        
    def xywh_to_xyxy(self):
        self.mode ="xyxy"
        
    def area(self):
        return self.w * self.h
    
    def is_in(self, other):
        return self.top_left[0] >= other.top_left[0] and self.top_left[1] >= other.top_left[1] and self.w <= other.w and self.h <= other.h
    
box1 = bbox([0,0,4,4], "xyxy")
box2 = bbox([1,1,2,2], "xywh")
box2.is_in(box1)

True


##### 4.b

create objects called Face, Violation, Person that are specials cases of bounding boxes. Face is a box with name, Violation is box with and id. Person is an object that has a location given by a box, name given by a name of face object and violations given by list of violation id of violation object. Person object two methods 1) get_name that takes in list of faces and returns name of the face inside it's location box and sets the person's name if found. 2) get_violation that get the  violation boxes insided the person's location and sets the person's violations attribute. 
use inheritance accordingly

In [31]:
class Face(bbox):
    # bbox with name
    def __init__(self, lst, mode, name):
        super().__init__(lst, mode)
        self.name = name

class Violation(bbox):
    # bbox with id
    def __init__(self, lst, mode, id_):
        super().__init__(lst, mode)
        self.id = id_

class Person():
    # takes location bbox as param
    def __init__(self, location):
        self.location = location
        self.name = ""
        self.violations = []
    def get_name(faces):
        for face in faces:
            if face.is_in(location):
                self.name = face.name
                return face.name
    def get_violation(violations):
        for violation in violations:
            if violation.is_in(location) and violation not in self.violations:
                self.violations += violation
                